[build]
  # Diret칩rio de onde o c칩digo ser치 compilado
  base = "publish"
  # Comando para construir o site
  command = "yarn &&yarn build"
  # Pasta onde o comando de build ser치 executado
  publish = "dist"