[build]
  # Diret칩rio de onde o c칩digo ser치 compilado
  base = "public"
  # Comando para construir o site
  command = "yarn build"
  # Pasta onde o comando de build ser치 executado
  publish = "public"